group {
    col.border_active = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.border_inactive = rgba(595959aa)
    
    groupbar {
        font_family = sans-serif
        font_size = 10
        gradients = true
        col.active = rgba(33ccffaa)
        col.inactive = rgba(595959aa)
    }
}