################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
#monitor=,preferred,auto,auto

##################################################
# Ana Ekran (Laptop - 144Hz)
#monitor=eDP-1, 1920x1080@144, 0x0, 1
# İkinci Ekran (ViewSonic - 165Hz) - Sağ tarafta
#monitor=DP-1, 1920x1080@164.92, 1920x0, 1
##################################################

# Laptop ekranı her zaman en yüksekte kalsın
monitor=eDP-1, highres@high, 0x0, 1

# Harici monitör (hangisi takılırsa takılsın) en yüksekte çalışsın
monitor=DP-1, highres@high, 1920x0, 1