###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = thunar
#$fileManager = dolphin
$browser = zen-browser
$menu = rofi -show drun
$editor = kate
$pdfViewer = okular

##########################
### DEFAULT APPS (.desktop)
##########################

# ls /usr/share/applications/ | grep -i UYGULAMAADI

$browserDesktop = zen.desktop
$fileManagerDesktop = thunar.desktop
$editorDesktop = org.kde.kate.desktop
$pdfViewerDesktop = okular.desktop

exec-once = xdg-mime default $browserDesktop x-scheme-handler/http
exec-once = xdg-mime default $browserDesktop x-scheme-handler/https
exec-once = xdg-mime default $fileManagerDesktop inode/directory
exec-once = xdg-mime default $editorDesktop text/plain
exec-once = xdg-mime default $pdfViewerDesktop application/pdf