##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# Satty (screenshot editor)
windowrule {
    name = float-satty
    match:class = com.gabm.satty
    float = yes
}

# XDG Desktop Portalları
windowrule {
    name = float-xdg-gtk
    match:class = xdg-desktop-portal-gtk
    float = yes
}

windowrule {
    name = float-xdg-hyprland
    match:class = xdg-desktop-portal-hyprland
    float = yes
}

# Sistem Araçları
windowrule {
    name = float-pavucontrol
    match:class = pavucontrol
    float = yes
}

windowrule {
    name = float-pavucontrol-org
    match:class = org.pulseaudio.pavucontrol
    float = yes
}

windowrule {
    name = float-blueman
    match:class = blueman-manager
    float = yes
}

windowrule {
    name = float-polkit
    match:class = org.kde.polkit-kde-authentication-agent-1
    float = yes
}



# Steam oyunlarının tam ekran açılması için kurallar
#windowrule {
#    name = fullscreen-steam-games
#    match:class = ^steam_app_\d+$
#    fullscreen = yes
#    workspace = unset
#}

#windowrule {
#    name = fullscreen-gamescope
#    match:class = ^gamescope$
#    fullscreen = yes
#    workspace = unset
#}

# Waybar arka plan bulanıklaştırma (blur)
blurls = waybar