general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = true
    hide_cursor = true # Kilit ekranında mouse imlecini gizler, daha temiz bir görüntü sunar
}

background {
    monitor =
    path = screenshot
    color = rgba(9, 9, 11, 1.0) # Rofi temamızdaki Derin Uzay Siyahı
    
    # Premium Cam Efekti (Frosted Glass / Glassmorphism)
    blur_passes = 3
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# Saat
label {
    monitor =
    text = $TIME
    color = rgba(250, 250, 250, 1.0)
    font_size = 120
    font_family = Inter Bold
    position = 0, 120
    halign = center
    valign = center
    shadow_passes = 2
    shadow_size = 4
}

# Tarih
label {
    monitor =
    text = cmd[update:18000000] echo "<b> "$(date +'%A, %d %B')" </b>"
    color = rgba(200, 200, 200, 1.0)
    font_size = 22
    font_family = Inter Medium
    position = 0, 10
    halign = center
    valign = center
}

# Karşılama Mesajı
label {
    monitor =
    text = Merhaba, $USER
    color = rgba(250, 250, 250, 0.8)
    font_size = 16
    font_family = Inter
    position = 0, -80
    halign = center
    valign = center
}

# Şifre Kutusu
input-field {
    monitor =
    size = 280, 55
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.2
    dots_center = true
    
    # Cam (Glass) benzeri şeffaf kutu
    outer_color = rgba(255, 255, 255, 0.1)
    inner_color = rgba(255, 255, 255, 0.05)
    font_color = rgba(250, 250, 250, 1.0)
    
    fade_on_empty = false
    placeholder_text = <i>Şifre...</i>
    hide_input = false
    
    rounding = 16 # Rofi ve Swaync temalarımızdaki ortak ovallik değeri
    
    position = 0, -150
    halign = center
    valign = center
}
