#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = tr
    numlock_by_default = true
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    repeat_rate = 50
    repeat_delay = 300

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    # Orta tık basılı tutularak fare hareketi ile sayfa kaydırmayı aktifleştir
    scroll_method = on_button_down
    scroll_button = 274 # Orta tuşun Linux'taki varsayılan donanım kodu

    touchpad {
        natural_scroll = true
    }
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace

# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
